name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'

categories:
  - title: 'âœ¨ New Features'
    labels: ['âœ¨ feat', 'feature']
  - title: 'ğŸ Bug Fixes'
    labels: ['ğŸ fix', 'bugfix']
  - title: 'ğŸ”¨ Refactoring'
    labels: ['ğŸ”¨ refactor', 'refactor']
  - title: 'ğŸ“ƒ Documentation'
    labels: ['ğŸ“ƒ docs', 'documentation']
  - title: 'âš™ï¸ Configuration & Maintenance'
    labels: ['âš™ï¸ chore', 'chore']
  - title: 'âœ… Tests'
    labels: ['âœ… test', 'tests']
  - title: 'ğŸ¨ Style & Format'
    labels: ['ğŸ¨ style', 'style']
  - title: 'âš¡ Performance'
    labels: ['âš¡ perf', 'performance']

change-template: '- $TITLE (#$NUMBER) @$AUTHOR'

template: |
  ## ğŸš€ What's Changed
  
  $CHANGES
  
  **Full Changelog**: https://github.com/$OWNER/$REPOSITORY/compare/$PREVIOUS_TAG...v$RESOLVED_VERSION

no-changes-template: 'No changes in this release ğŸ‰'

version-resolver:
  major:
    labels: ['1ï¸âƒ£ major', 'breaking']
  minor:
    labels: ['2ï¸âƒ£ minor', 'enhancement']
  patch:
    labels: ['3ï¸âƒ£ patch', 'patch']
  default: patch